#classpath: list of jars and directories. byte code is stored here
#context-path: url part after domain/8080; which applies for all APIs.
#e.g. http://localhost:8080/journalApp/journal
#if same properties are present in cmd/application.properties/application.yml
#then precedence is cmd -> application.properties -> application.
#command line args -> java -jar jarFileName --server.port=9090

spring:
  application:
    name: journalApp

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    autoindex:
      create: true

server:
  port: 8080
  servlet:
    context-path: /journalApp

weather:
  api:
    key: ${WEATHER_API_KEY}